site_name: "HULK - Havana University Language for Kompilers"
site_url: https://matcom.githun.io/hulk
repo_url: https://github.com/matcom/hulk

remote_branch: master

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - navigation.top
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/matcom
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MatComRP
    - icon: fontawesome/brands/telegram
      link: https://t.me/matcom_cmp

copyright: CC 4.0 BY-NC-SA &copy; 2022 - School of Math and Computer Science, University of Havana

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Language Guide:
    - Expressions: guide/expressions.md
    - Functions: guide/functions.md
    - Variables: guide/variables.md
    - Conditionals: guide/conditionals.md
    - Loops: guide/loops.md
    - Types: guide/types.md
    - Type checking: guide/typing.md
    - Type inference: guide/inference.md
    - Protocols: guide/protocols.md
    - Iterables: guide/iterables.md
    - Vectors: guide/vectors.md
    - Functors: guide/functors.md
    - Macros: guide/macros.md

watch:
  - docs
