project:
  type: book

book:
  title: "Principles of Programming Languages Design and Implementation"
  subtitle: "Builing a Hulk Interpreter and Compiler"
  author: "Alejandro Piad Morffis"
  date: "today"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Frontend"
      chapters:
        - 01-dual-ancestry.qmd
        - 02-atomization.qmd
        - 03-structure.qmd
        - 04-evaluation.qmd
        - 05-binding.qmd
        - 06-shield.qmd
    - part: "Bridge"
      chapters:
        - 07-lowering.qmd
        - 08-transpiler.qmd
    - part: "Backend"
      chapters:
        - 09-metal-sandbox.qmd
        - 10-stack-machine.qmd
        - 11-heap-memory.qmd
        - 12-garbage-collector.qmd
        - 13-standard-library.qmd
        - 14-final-polish.qmd
  appendices:
    - appendix-hulk-syntax.qmd
    - instructors.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    favicon: images/hulk.png
    syntax-definitions:
      - ../syntax/hulk.xml
  pdf:
    output-file: hulk.pdf
    documentclass: scrreprt
    toc: true
