project:
  type: book

book:
  title: "Principles of Programming Languages"
  subtitle: "Design and Implementation (A 14-Week Journey)"
  author: "Alejandro Piad Morffis"
  date: "today"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "I. The Architect (Frontend - Python)"
      chapters:
        - 01-dual-ancestry.qmd
        - 02-atomization.qmd
        - 03-structure.qmd
        - 04-evaluation.qmd
        - 05-binding.qmd
        - 06-shield.qmd
    - part: "II. The Bridge (Intermediate Representation)"
      chapters:
        - 07-lowering.qmd
        - 08-transpiler.qmd
    - part: "III. The Engineer (Backend - Rust)"
      chapters:
        - 09-metal-sandbox.qmd
        - 10-stack-machine.qmd
        - 11-heap-memory.qmd
        - 12-garbage-collector.qmd
        - 13-standard-library.qmd
        - 14-final-polish.qmd
    - part: "Appendices"
      chapters:
        - appendix-hulk-syntax.qmd
        - instructors.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
  # pdf:
  #   documentclass: scrreprt
  #   toc: true
