project:
  type: book

book:
  title: "Principles of Programming Languages Design and Implementation"
  subtitle: "Builing a Hulk Interpreter and Compiler"
  author: "Alejandro Piad Morffis"
  date: "today"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Part 1: The Frontend"
      chapters:
        - 01-arithmetic-expressions.qmd
        - 02-strings-and-builtins.qmd
        - 03-variables-and-binding.qmd
        - 04-control-flow.qmd
        - 05-functions-and-recursion.qmd
        - 06-objects-and-classes.qmd
        - 07-type-checking-and-inference.qmd
    - part: "Part 2: The Backend"
      chapters:
        - 08-lowering-to-banner-ir.qmd
        - 09-the-metal-sandbox.qmd
        - 10-stack-machine.qmd
        - 11-object-representation-and-heap.qmd
        - 12-virtual-method-calls.qmd
        - 13-garbage-collector.qmd
        - 14-final-polish.qmd
  appendices:
    - appendix-hulk-syntax.qmd
    - appendix-banner.qmd
    - appendix-tooling.qmd
    - instructors.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    favicon: images/hulk.png
    syntax-definitions:
      - ../syntax/hulk.xml
      - ../syntax/banner.xml
  pdf:
    output-file: hulk.pdf
    documentclass: scrreprt
    toc: true
    syntax-definitions:
      - ../syntax/hulk.xml
      - ../syntax/banner.xml
