project:
  type: book
  output-dir: "../docs"

book:
  title: "The Hitchhiker's Guide to Compilers"
  author: "Alejandro Piad Morffis"
  date: "7/12/2024"
  cover-image: cover.png
  chapters:
    - index.qmd
    - part: Formal Language Theory
      chapters:
        - "theory/intro.qmd"
    - part: Lexers and Parsers
      chapters:
        - "parsing/intro.qmd"
    - part: Programing Languages
      chapters:
        - "semantics/intro.qmd"
    - part: Runtime Environments
      chapters:
        - "runtime/intro.qmd"
    - part: The HULK Programming Language
      chapters:
        - guide/intro.qmd
        - guide/expressions.md
        - guide/functions.md
        - guide/variables.md
        - guide/conditionals.md
        - guide/loops.md
        - guide/types.md
        - guide/typing.md
        - guide/inference.md
        - guide/protocols.md
        - guide/iterables.md
        - guide/vectors.md
        - guide/functors.md
        - guide/macros.md
  appendices:
    - instructors.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    epub-cover-image: cover.png
